export const categories = [
  "Accounting",
  "Airport",
  "Amusement Park",
  "Aquarium",
  "Art Gallery",
  "ATM",
  "Bakery",
  "Bank",
  "Bar",
  "Beauty Salon",
  "Bicycle Store",
  "Book Store",
  "Bowling Alley",
  "Bus Station",
  "Cafe",
  "Campground",
  "Car Dealer",
  "Car Rental",
  "Car Repair",
  "Car Wash",
  "Casino",
  "Cemetery",
  "Church",
  "City Hall",
  "Clothing Store",
  "Convenience Store",
  "Courthouse",
  "Dentist",
  "Department Store",
  "Doctor",
  "Drugstore",
  "Electrician",
  "Electronics Store",
  "Embassy",
  "Fire Station",
  "Florist",
  "Funeral Home",
  "Furniture Store",
  "Gas Station",
  "Gym",
  "Hair Care",
  "Hardware Store",
  "Hindu Temple",
  "Home Goods Store",
  "Hospital",
  "Insurance Agency",
  "Jewelry Store",
  "Laundry",
  "Lawyer",
  "Library",
  "Light Rail Station",
  "Liquor Store",
  "Local Government Office",
  "Locksmith",
  "Lodging",
  "Meal Delivery",
  "Meal Takeaway",
  "Mosque",
  "Movie Rental",
  "Movie Theater",
  "Moving Company",
  "Museum",
  "Night Club",
  "Painter",
  "Park",
  "Parking",
  "Pet Store",
  "Pharmacy",
  "Physiotherapist",
  "Plumber",
  "Police",
  "Post Office",
  "Primary School",
  "Real Estate Agency",
  "Restaurant",
  "Roofing Contractor",
  "RV Park",
  "School",
  "Secondary School",
  "Shoe Store",
  "Shopping Mall",
  "Spa",
  "Stadium",
  "Storage",
  "Store",
  "Subway Station",
  "Supermarket",
  "Synagogue",
  "Taxi Stand",
  "Tourist Attraction",
  "Train Station",
  "Transit Station",
  "Travel Agency",
  "University",
  "Veterinary Care",
  "Zoo",
];
